using System.Collections.Generic;
using Abp.Configuration;

namespace Ncc.Configuration
{
    public class AppSettingProvider : SettingProvider
    {
        public override IEnumerable<SettingDefinition> GetSettingDefinitions(SettingDefinitionProviderContext context)
        {
            return new[]
            {
                new SettingDefinition(AppSettingNames.UiTheme, "red", scopes: SettingScopes.Application | SettingScopes.Tenant | SettingScopes.User, isVisibleToClients: true),
                new SettingDefinition(AppSettingNames.ClientAppId,"null",scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SecretRegisterCode,"RatLaBiMat",scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.DaysAbsencePerYear,"0",scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.DayWorkingHour, "8", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHNEndAt, "12:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHNStartAt, "08:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHNStartAt, "13:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHNEndAt, "17:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningDNEndAt, "12:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningDNStartAt, "8:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonDNStartAt, "13:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonDNEndAt, "17:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHCMEndAt, "12:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHCMStartAt, "08:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHCMStartAt, "13:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHCMEndAt, "17:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningVinhEndAt, "12:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningVinhStartAt, "08:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonVinhStartAt, "13:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonVinhEndAt, "17:30", scopes:SettingScopes.Application| SettingScopes.Tenant),

                new SettingDefinition(AppSettingNames.MorningHNWorking, "3.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningDNWorking, "4", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHCMWorking, "3.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningVinhWorking, "3.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHNWorking, "4.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonDNWorking, "4", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHCMWorking, "4.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonVinhWorking, "4.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.Holidays, "", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MinWorkingDay, "7", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MinHalfWorkingDay, "3", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LimitedMinutes, "15", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailHR, "thuy.nguyenxuan.ncc@gmail.com", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.HRMUri,"http://hrm-api.dev.nccsoft.vn/",scopes:SettingScopes.Application|SettingScopes.Tenant),
                //new SettingDefinition(AppSettingNames.ProjectUri,"http://project-api.dev.nccsoft.vn/",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ProjectUri,"http://172.16.14.166:21028/",scopes:SettingScopes.Application|SettingScopes.Tenant),
                //new SettingDefinition(AppSettingNames.HRMUri,"http://localhost:21024/",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailSaoDo, "saodo@ncc.asia", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendEmailToSaoDo, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailHRDN, "thuy.nguyenxuan@ncc.asia", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailHRHCM, "thuy.nguyenxuan@ncc.asia", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailHRVinh, "thuy.nguyenxuan@ncc.asia", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ProjectTaskId, "20078", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SecurityCode, "Xnsks4@llslhl%hjsksCCHHA145", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockDayOfUser, "Monday", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockHourOfUser, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockMinuteOfUser, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockDayOfPM, "Tuesday", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockHourOfPM, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockMinuteOfPM, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockDayAfterUnlock, "Thursday", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockHourAfterUnlock, "3", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockMinuteAfterUnlock, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LogTimesheetInFuture, "false" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MaxTimeSheetHourPerDay, "16" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.DayAllowLogTimesheetInFuture, "3" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AutoSubmitTimesheet, "true" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AutoSubmitAt, "Monday" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AutoSubmitAtHour, "8" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CheckInInternalAtHour, "11" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.DateToLockTimesheetOfLastMonth, "5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                //new SettingDefinition(AppSettingNames.AccountIDCheckIn, "dd0f2097-ad1a-4575-be15-a8bba7b559f2" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                //new SettingDefinition(AppSettingNames.SercurityCodeCheckIn, "6kkCZQja9Gn27kTiv" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                //new SettingDefinition(AppSettingNames.UrlServerCheckIn, "http://172.16.10.126:8000/" , scopes:SettingScopes.Application| SettingScopes.Tenant),				
				new SettingDefinition(AppSettingNames.CheckInInternalUrl, "https://checkin.nccsoft.vn/" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CheckInInternalAccount, "dd0f2097-ad1a-4575-be15-a8bba7b559f2" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CheckInInternalXSecretKey, "9fqKUaGGF9vLvcCj" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.HRMSecretCode, "Xnsks4@llslhl%hjsksCCHHA145" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ProjectSecretCode, "Uqhfwwg%fyef@HUSAA744fiegyeR" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.UserLevelSetting, "" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.PercentSalaryProbationary, "85", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.KomuUri, "http://172.16.11.90:3000/", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.KomuSecretCode, "6kkCZQja9Gn27kTiv", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.KomuChannelIdDevMode, "1011469135198294036", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.KomuUserNameDevMode, "", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.WFHSetting, "3", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AllowInternToWorkRemote, "false", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.OpenTalkTaskId, "20078", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendEmailTimesheet, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendEmailRequest, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendKomuSubmitTimesheet, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EnableNofityKomuCheckInOutPunishment, "false", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendKomuRequest, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyAtHour,"14",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyOnDates,"10,13,15",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyReviewDeadline,"15",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyToChannels,"928939241675833404,963658600214061096",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyPenaltyFee,"50.000",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TotalTimeAbsenceTime,"2",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.WeeksCanUnlockBefor,"1",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NofityKomuCheckInOutPunishmentAtHour, "14", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NofityKomuCheckInOutPunishmentToChannelId, "", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.PercentOfTrackerOnWorking, "90", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CheckInCheckOutPunishmentSetting, "[{\"id\":0,\"name\":\"Không bị phạt\",\"note\":\"Nhân viên check in và check out đúng\",\"money\":0},{\"id\":1,\"name\":\"Đi muộn\",\"note\":\"Nhân viên đi muộn có check in và không check out(tracker đủ) hoặc có check out\",\"money\":20000},{\"id\":2,\"name\":\"Không CheckIn\",\"note\":\"Nhân viên không check in, không check out(tracker đủ)\",\"money\":30000},{\"id\":3,\"name\":\"Không CheckOut\",\"note\":\"Nhân viên check in đúng giờ và không checkout(tracker không đủ)\",\"money\":30000},{\"id\":4,\"name\":\"Đi muộn và Không CheckOut\",\"note\":\"Nhân viên có check in muộn và không có check out(tracker không đủ)\",\"money\":50000},{\"id\":5,\"name\":\"Không CheckIn và không CheckOut\",\"note\":\"Nhân viên không check in và không check out(tracker không đủ)\",\"money\":100000}]", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyAtHour, "10", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyOnDates, "10,11,12,13,14,15", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyDeadline, "15", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyToChannels, "963658600214061096", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimesCanLateAndEarlyInMonth, "4", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimesCanLateAndEarlyInWeek, "2", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.GenerateDataOnDate,"6",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TeamBuildingMoney,"100000",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.BillPercentage,"90",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimeStartChangingCheckinToCheckout,"15:00", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimeStartChangingCheckinToCheckoutEnable,"false", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimeStartChangingCheckinToCheckoutCaseOffAfternoon,"11:00", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyAtHour, "11", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyOnDates, "1,2,3,4,5", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyToChannels, "928939241675833404,963658600214061096", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyTimePeriodWithPendingRequest, "-30", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveRequestOffNotifyEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveRequestOffNotifyAtHour, "10", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveRequestOffNotifyToChannels, "928939241675833404,963658600214061096", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveRequestOffNotifyTimePeriodWithPendingRequest, "-30", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageRequestPendingTeamBuildingToHREnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageRequestPendingTeamBuildingToHRAtHour, "10", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageRequestPendingTeamBuildingToHRToChannels, "928939241675833404,963658600214061096", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageRequestPendingTeamBuildingToHREmail, "hr@ncc.asia", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftAtHour, "11", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftToChannels, "928939241675833404,963658600214061096", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftToHREmail, "hr@ncc.asia", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftTimePeriod, "-7", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MoneyPMUnlockTimeSheet,"20000",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageToPunishUserEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageToPunishUserAtHour, "11", scopes: SettingScopes.Application|SettingScopes.Tenant),
            };
        }
    }
}
